services:
  provider:
    build:
      context: ./provider-service
      dockerfile: Dockerfile
    container_name: provider-service
    ports:
      - "8081:8081"
    environment:
      - PROVIDER_ID=provider-1
    networks:
      - lab-network

  consumer:
    build:
      context: ./consumer-service
      dockerfile: Dockerfile
    container_name: consumer-service
    ports:
      - "8080:8080"
    environment:
      - PROVIDER_URL=http://provider:8081
    depends_on:
      - provider
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
