services:
  broker:
    build:
      context: ./broker-service
      dockerfile: Dockerfile
    container_name: broker
    ports:
      - "8082:8082"
    networks:
      - lab-network

  nginx:
    image: nginx:alpine
    container_name: load-balancer
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - provider-1
      - provider-2
      - provider-3
    networks:
      - lab-network

  provider-1:
    build:
      context: ./provider-service
      dockerfile: Dockerfile
    container_name: provider-1
    environment:
      - PROVIDER_ID=provider-1
      - BROKER_URL=http://broker:8082
    depends_on:
      - broker
    networks:
      - lab-network

  provider-2:
    build:
      context: ./provider-service
      dockerfile: Dockerfile
    container_name: provider-2
    environment:
      - PROVIDER_ID=provider-2
      - BROKER_URL=http://broker:8082
    depends_on:
      - broker
    networks:
      - lab-network

  provider-3:
    build:
      context: ./provider-service
      dockerfile: Dockerfile
    container_name: provider-3
    environment:
      - PROVIDER_ID=provider-3
      - BROKER_URL=http://broker:8082
    depends_on:
      - broker
    networks:
      - lab-network

  consumer:
    build:
      context: ./consumer-service
      dockerfile: Dockerfile
    container_name: consumer-service
    ports:
      - "8080:8080"
    environment:
      - PROVIDER_URL=http://nginx:80
      - BROKER_URL=http://broker:8082
    depends_on:
      - nginx
      - broker
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
